CREATE TABLE `FAKULTAS`  (
  `ID` int NOT NULL,
  `ILMU_KOMPUTER` varchar(255) NULL,
  `HUKUM` varchar(255) NULL,
  `PSIKOLOGI` varchar(255) NULL,
  `MANAGEMENT` varchar(255) NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `KAMPUS`  (
  `ID` int NOT NULL,
  `ESA_UNGGUL` varchar(255) NULL,
  `UNTAR` varchar(255) NULL,
  `UNTARA` varchar(255) NULL,
  `UMT` varchar(255) NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `LULUS`  (
  `ID` int NOT NULL,
  `LULUS` varchar(255) NULL,
  `TIDAK LULUS` varchar(255) NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `MAHASISWA`  (
  `ID` int NOT NULL,
  `NAMA` varchar(255) NULL,
  `NIM` varchar(255) NULL,
  `STATUS` varchar(255) NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `MATA_KULIAH`  (
  `ID` int NOT NULL,
  `KALKULUS` varchar(255) NULL,
  `KEWIRAUSAHAAN` varchar(255) NULL,
  `RPL` varchar(255) NULL,
  `BASIS_DATA` varchar(255) NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `NILAI`  (
  `ID` int NOT NULL,
  `86` varchar(255) NULL,
  `75` varchar(255) NULL,
  `82` varchar(255) NULL,
  `85` varchar(255) NULL,
  `90` varchar(255) NULL,
  PRIMARY KEY (`ID`)
);

ALTER TABLE `FAKULTAS` ADD CONSTRAINT `fk_FAKULTAS_MATA_KULIAH_1` FOREIGN KEY (`ID`) REFERENCES `MATA_KULIAH` (`ID`);
ALTER TABLE `KAMPUS` ADD CONSTRAINT `fk_KAMPUS_FAKULTAS_1` FOREIGN KEY (`ID`) REFERENCES `FAKULTAS` (`ID`);
ALTER TABLE `MAHASISWA` ADD CONSTRAINT `fk_MAHASISWA_KAMPUS_1` FOREIGN KEY (`ID`) REFERENCES `KAMPUS` (`ID`);
ALTER TABLE `MATA_KULIAH` ADD CONSTRAINT `fk_MATA_KULIAH_NILAI_1` FOREIGN KEY (`ID`) REFERENCES `NILAI` (`ID`);
ALTER TABLE `NILAI` ADD CONSTRAINT `fk_NILAI_LULUS_1` FOREIGN KEY (`ID`) REFERENCES `LULUS` (`ID`);

